<?php
/**
 * QR Code Configuration
 * This file can be auto-generated by Admin menu or manually edited
 * Note: Do NOT output anything from this file to avoid corrupting PDF streams.
 */

// Load main config for BASEURL and SECRET_KEY
if (!defined('BASEURL')) {
    require_once __DIR__ . '/config.php';
}

// Fallback SECRET_KEY if not defined in config.php (for backward compatibility)
if (!defined('SECRET_KEY')) {
    define('SECRET_KEY', 'default_qr_secret_change_me_' . __DIR__);
}

// Default QR settings (can be overridden by admin panel)
if (!defined('QR_ENABLED')) {
    define('QR_ENABLED', true); // Set false to disable QR generation
}
if (!defined('QR_API_PROVIDER')) {
    define('QR_API_PROVIDER', 'quickchart'); // quickchart, goqr, qrserver, or custom
}
if (!defined('QR_API_QRSERVER')) {
    define('QR_API_QRSERVER', 'https://api.qrserver.com/v1/create-qr-code/');
}
if (!defined('QR_CUSTOM_URL')) {
    define('QR_CUSTOM_URL', '');
}
if (!defined('QR_SIZE')) {
    define('QR_SIZE', '150'); // pixels or '200x200' format
}
if (!defined('QR_MARGIN')) {
    define('QR_MARGIN', '1'); // margin around QR
}
if (!defined('QR_ERROR_CORRECTION')) {
    define('QR_ERROR_CORRECTION', 'M'); // L, M, Q, H
}
if (!defined('QR_WEBSITE_URL')) {
    define('QR_WEBSITE_URL', BASEURL);
}
if (!defined('QR_DISPLAY_SIZE')) {
    define('QR_DISPLAY_SIZE', '50px'); // Size in PDF
}
if (!defined('QR_TOKEN_EXPIRY')) {
    define('QR_TOKEN_EXPIRY', 365); // days, 0 = never
}
if (!defined('QR_POSITION')) {
    define('QR_POSITION', 'bottom-right'); // Position in PDF
}
if (!defined('QR_DISPLAY_TEXT')) {
    define('QR_DISPLAY_TEXT', 'Scan untuk validasi');
}
if (!defined('QR_TOKEN_SALT')) {
    // Use SECRET_KEY from config.php as default salt
    define('QR_TOKEN_SALT', SECRET_KEY);
}

// PDF display settings final resolution (avoid double define)
if (!defined('QR_PDF_SIZE')) {
    // Prefer admin provided display size, fallback 60px
    $displaySize = defined('QR_DISPLAY_SIZE') ? QR_DISPLAY_SIZE : '60px';
    if (is_string($displaySize)) {
        $displaySize = (int) str_replace(['px',' '],'',$displaySize) ?: 60;
    }
    define('QR_PDF_SIZE', $displaySize);
}
if (!defined('QR_PDF_POSITION')) {
    define('QR_PDF_POSITION', defined('QR_POSITION') ? QR_POSITION : 'bottom-right');
}

/**
 * Generate unique token for QR validation
 * Compatible with admin panel config
 */
function generateQRToken($id, $type, $identifier = '') {
    // Stable (non base64) hex token keeps URL shorter and avoids non-url-safe characters
    $data = $id . '|' . $type . '|' . $identifier . '|' . date('YmdHis');
    return hash('sha256', $data . '_' . QR_TOKEN_SALT);
}

/**
 * Get QR Code API URL based on provider
 */
function getQRCodeApiUrl($data) {
    $encodedData = urlencode($data);
    $size = QR_SIZE;
    // Normalize size format for different providers
    $sizeStr = is_string($size) ? trim($size) : (string)(int)$size;
    $hasX = strpos($sizeStr, 'x') !== false || strpos($sizeStr, 'X') !== false;
    $num = (int) $sizeStr;
    $sizeQuickchart = $hasX ? (int) explode('x', strtolower($sizeStr))[0] : $num; // quickchart expects single number
    $sizePair = $hasX ? strtolower($sizeStr) : ($num > 0 ? ($num . 'x' . $num) : '200x200');
    $margin = QR_MARGIN;
    
    switch (QR_API_PROVIDER) {
        case 'quickchart':
            return "https://quickchart.io/qr?text={$encodedData}&size={$sizeQuickchart}&margin={$margin}";
        case 'goqr':
            return "https://api.qrserver.com/v1/create-qr-code/?data={$encodedData}&size={$sizePair}&margin={$margin}";
        case 'qrserver':
            return "https://api.qrserver.com/v1/create-qr-code/?data={$encodedData}&size={$sizePair}&margin={$margin}";
        default:
            return "https://quickchart.io/qr?text={$encodedData}&size={$sizeQuickchart}";
    }
}

/**
 * Generate QR Code for PDF documents
 */
function generatePDFQRCode($docType, $docId, $additionalData = []) {
    try {
        // Create unique token
        $identifier = $docId . '_' . uniqid();
        $token = generateQRToken($docId, $docType, $identifier);
        
        // Persist token for validation (DB), safe include without output
        try {
            $APPROOT = dirname(__DIR__);
            // Prevent accidental output corrupting PDF
            $____ob = ob_get_level();
            ob_start();
            require_once $APPROOT . '/app/core/Database.php';
            require_once $APPROOT . '/app/models/QRValidation_model.php';
            ob_end_clean();
            if (ob_get_level() > $____ob) { while (ob_get_level() > $____ob) { ob_end_clean(); } }

            if (class_exists('QRValidation_model')) {
                $qrModel = new QRValidation_model();
                // Ensure tables exist (no-op if already created)
                $qrModel->ensureTables();
                $expiryDays = defined('QR_TOKEN_EXPIRY') ? (int) QR_TOKEN_EXPIRY : 365;
                // Store meta limited to safe scalars
                $meta = [];
                if (is_array($additionalData)) {
                    foreach ($additionalData as $k => $v) {
                        if (is_scalar($v)) { $meta[$k] = $v; }
                    }
                }
                // Persist
                $qrModel->storeToken((string)$docType, (string)$docId, (string)$identifier, (string)$token, $expiryDays, $meta);
            }
        } catch (Throwable $____e) {
            // Do not break PDF on DB errors; log server-side only
            error_log('QR persist error: ' . $____e->getMessage());
        }
        
        // Validation URL (public endpoint, avoid auth-protected routes)
        // Use direct file URL with query params to prevent router/login redirects
        $base = rtrim(QR_WEBSITE_URL, '/');
        $validationUrl = $base . '/validate.php?type=' . rawurlencode($docType) . '&token=' . rawurlencode($token);
        
        // Get QR Code image with timeout
        $qrApiUrl = getQRCodeApiUrl($validationUrl);
        
        // Use stream context with timeout to prevent hanging
        $context = stream_context_create([
            'http' => [
                'timeout' => 3,  // 3 seconds timeout
                'ignore_errors' => true
            ]
        ]);
        
        $imageData = @file_get_contents($qrApiUrl, false, $context);
        
        if ($imageData !== false && !empty($imageData)) {
            $head8 = substr($imageData, 0, 8);
            if ($head8 === "\x89PNG\x0D\x0A\x1A\x0A") {
                return 'data:image/png;base64,' . base64_encode($imageData);
            }
            if (substr($imageData,0,2) === "\xFF\xD8") {
                return 'data:image/jpeg;base64,' . base64_encode($imageData);
            }
        }
        
        // Fallback SVG if API fails
        return 'data:image/svg+xml;base64,' . base64_encode(
            '<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80">' .
            '<rect width="80" height="80" fill="#f0f0f0"/>' .
            '<text x="40" y="45" text-anchor="middle" font-size="12" fill="#666">QR Code</text>' .
            '</svg>'
        );
    } catch (Exception $e) {
        error_log('QR Code generation failed: ' . $e->getMessage());
        // Return empty instead of failing PDF generation
        return '';
    }
}

/**
 * Get QR Code HTML for PDF (positioned)
 */
function getQRCodeHTML($qrBase64, $position = null) {
    if (empty($qrBase64)) return '';
    
    $position = $position ?? QR_PDF_POSITION;
    $size = QR_PDF_SIZE;
    // Normalize size to numeric pixels
    if (is_string($size)) {
        $size = (int) str_replace(['px', ' '], '', $size);
    }
    
    $styles = [
        'top-right' => 'position: absolute; top: 10px; right: 10px;',
        'top-left' => 'position: absolute; top: 10px; left: 10px;',
        'bottom-right' => 'position: absolute; bottom: 10px; right: 10px;',
        'bottom-left' => 'position: absolute; bottom: 10px; left: 10px;',
    ];
    
    $style = $styles[$position] ?? $styles['bottom-right'];
    
    return '<div style="' . $style . '">
        <img src="' . $qrBase64 . '" style="display:block;width:' . $size . 'px;height:' . $size . 'px;" alt="QR Validation"/>
        <div style="font-size: 7px; text-align: center; color: #666; margin-top: 2px;">Scan untuk validasi</div>
    </div>';
}
